name: Build LaTeX paper and create release
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: dsl-for-visualizing-geospatial-data.tex
          working_directory: paper/
          args: -pdf -bibtex -latexoption=-file-line-error -latexoption=-interaction=nonstopmode
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest
          release_name: built from latest commit
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: paper/dsl-for-visualizing-geospatial-data.pdf
          asset_name: dsl-for-visualizing-geospatial-data.pdf
          asset_content_type: application/pdf
